import MessageToast from "sap/m/MessageToast";
import type Event from "sap/ui/base/Event";
import Fragment from "sap/ui/core/Fragment";
import ControllerExtension from "sap/ui/core/mvc/ControllerExtension";
import * as testXlsx from "xlsx";
declare const XLSX: any;

export default ControllerExtension.extend(
  "booksui.ext.controller.customActions",
  {
    oDialogFragment: undefined as Fragment,

    onUploadExcel(oEvent: Event) {
      console.log("=============>", testXlsx);
      if (!this.oDialogFragment) {
        Fragment.load({
          name: "booksui.ext.fragment.UploadExcelDialog",
          controller: this,
        }).then((oDialog) => {
          this.oDialogFragment = oDialog;
          this.oDialogFragment.open();
        });
      }
    },

    onCloseDialog: async function () {
      this.oDialogFragment.destroy();
      this.oDialogFragment = undefined;
      this._file = null;
    },

    onAfterItemAdded: function (oEvent) {
      this._file = oEvent.getParameter("item").getFileObject();
      if (this._file) {
        MessageToast.show(
          "File '" + this._file.name + "' is ready for upload.",
        );
      }
      var oUploadButton = this.oDialogFragment.getBeginButton();
      if (oUploadButton) {
        oUploadButton.setEnabled(!!this._file);
      }
    },

    onAfterItemRemoved: function (oEvent) {
      this._file = null;
      this.oDialogFragment.then(function (oDialog) {
        var oUploadButton = oDialog.getBeginButton();
        if (oUploadButton) {
          oUploadButton.setEnabled(false);
        }
      });
      MessageToast.show("File removed.");
    },

    onUploadPress: function () {
      if (!this._file) {
        MessageToast.show("Please select a file first.");
        return;
      }

      var oReader = new FileReader();
      oReader.onload = function (e) {
        try {
          var data = e.target.result;
          var workbook = XLSX.read(data, { type: "buffer" });
          var sheetName = workbook.SheetNames[0];
          var excelData = XLSX.utils.sheet_to_row_object_array(
            workbook.Sheets[sheetName],
          );

          if (excelData.length > 0) {
            this._callOdataService(excelData);
          } else {
            MessageToast.show("No data found in the Excel file.");
          }
        } catch (error) {
          MessageToast.show("Error reading Excel file: " + error.message);
        }
      }.bind(this);

      oReader.readAsArrayBuffer(this._file);
    },

    _callOdataService: async function (excelData) {
      const oModel: any = this.getView().getModel();
      var oListBinding = oModel.bindList("/Books");
      excelData.forEach(function (rowData, index) {
        // IMPORTANT: Make sure your Excel column headers match exactly
        var oPayload = {
          //EmpID: rowData.EmployeeID.toString(), auto generated by Early Numbering in RAP Application
          ID: index + 1 + 100,
          title: rowData["ICAO"].toString(),
          stock: index + 10 * 2,
        };
        // The create operation is performed on the ListBinding instance.
        oListBinding.create(oPayload);
      });

      MessageToast.show("Uploading " + excelData.length + " records...");

      try {
        const results = await oModel.submitBatch("$auto");
        console.log(results);
        this.base.getExtensionAPI().refresh(); // Refresh the table to show new data
        this.onCloseDialog();
      } catch (error) {
        MessageToast.show("Error during upload: " + error.message);
      }
    },
  },
);
